name: github-pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      # run build script
      - name: Build site
        run: pnpm build

      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          repo: "dimrich/swc-ainag"
          target_branch: gh-pages
          build_dir: src/.vuepress/dist
          fqdn: "sorrywecan.ainag.com"
        env:
          #           @see https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          GH_PAT: ${{ secrets.GH_PAT }}